kernel/drivers/soc/qcom/cmd-db.ko
kernel/drivers/virt/gunyah/gh_msgq.ko
kernel/drivers/virt/gunyah/gh_rm_drv.ko
kernel/drivers/soc/qcom/smem.ko
kernel/drivers/soc/qcom/minidump.ko
kernel/kernel/trace/qcom_ipc_logging.ko
kernel/drivers/soc/qcom/soc_sleep_stats.ko
kernel/drivers/soc/qcom/boot_stats.ko
kernel/drivers/soc/qcom/socinfo.ko
kernel/drivers/hwspinlock/qcom_hwspinlock.ko
