kernel/drivers/regulator/debug-regulator.ko
kernel/drivers/regulator/proxy-consumer.ko
:kernel/drivers/soc/qcom/cmd-db.ko
:kernel/kernel/trace/qcom_ipc_logging.ko
kernel/drivers/soc/qcom/qcom_rpmh.ko
kernel/drivers/regulator/rpmh-regulator.ko
kernel/drivers/clk/qcom/gdsc-regulator.ko
kernel/drivers/clk/qcom/clk-qcom.ko
kernel/drivers/clk/qcom/clk-dummy.ko
kernel/drivers/clk/qcom/clk-rpmh.ko
kernel/drivers/clk/qcom/gcc-sc8180x.ko
kernel/drivers/clk/qcom/gcc-sm8150.ko
kernel/drivers/clk/qcom/dispcc-sm8250.ko
kernel/drivers/interconnect/qcom/icc-debug.ko
kernel/drivers/interconnect/qcom/icc-bcm-voter.ko
kernel/drivers/interconnect/qcom/icc-rpmh.ko
kernel/drivers/interconnect/qcom/qnoc-qos.ko
kernel/drivers/interconnect/qcom/qnoc-sc8180x.ko
kernel/drivers/interconnect/qcom/qnoc-sm8150.ko
kernel/drivers/iommu/qcom_iommu_util.ko
kernel/drivers/iommu/arm/arm-smmu/arm_smmu.ko
