:kernel/drivers/firmware/qcom-scm.ko
kernel/drivers/soc/qcom/mdt_loader.ko
:kernel/kernel/trace/qcom_ipc_logging.ko
kernel/drivers/irqchip/qcom-pdc.ko
kernel/drivers/pinctrl/qcom/pinctrl-msm.ko
kernel/drivers/pinctrl/qcom/pinctrl-sdmshrike.ko
kernel/drivers/pinctrl/qcom/pinctrl-sm8150.ko
kernel/drivers/pinctrl/qcom/pinctrl-slpi.ko
kernel/drivers/pinctrl/pinctrl-sx150x.ko
kernel/drivers/pinctrl/qcom/pinctrl-spmi-gpio.ko
