>mask=0
:kernel/drivers/soc/qcom/qcom_rpmh.ko
kernel/drivers/interconnect/qcom/icc-debug.ko
kernel/drivers/interconnect/qcom/icc-bcm-voter.ko
kernel/drivers/interconnect/qcom/icc-rpmh.ko
kernel/drivers/interconnect/qcom/qnoc-qos.ko
:kernel/drivers/clk/qcom/dispcc-sm8250.ko
kernel/drivers/interconnect/qcom/qnoc-sc8180x.ko
kernel/drivers/interconnect/qcom/qnoc-sm8150.ko
kernel/drivers/net/pcs/pcs_xpcs.ko
kernel/drivers/net/phy/micrel.ko
:kernel/kernel/trace/qcom_ipc_logging.ko
kernel/net/qrtr/qrtr.ko
