:kernel/drivers/regulator/debug-regulator.ko
kernel/drivers/regulator/stub-regulator.ko
kernel/drivers/base/regmap/regmap-spmi.ko
kernel/drivers/mfd/qcom-spmi-pmic.ko
kernel/drivers/nvmem/nvmem_qcom-spmi-sdam.ko
kernel/drivers/regulator/fixed.ko
kernel/drivers/regulator/qti-fixed-regulator.ko
kernel/drivers/power/reset/reboot-mode.ko
kernel/drivers/power/reset/qcom-pon.ko
