:kernel/drivers/soc/qcom/qcom_rpmh.ko
kernel/drivers/soc/qcom/dcvs/dcvs_fp.ko
:kernel/drivers/interconnect/qcom/qnoc-sc8180x.ko
:kernel/drivers/interconnect/qcom/qnoc-sm8150.ko
kernel/drivers/soc/qcom/dcvs/qcom-dcvs.ko
kernel/drivers/mailbox/qcom-apcs-ipc-mailbox.ko
:kernel/drivers/mailbox/msm_qmp.ko
:kernel/drivers/clk/qcom/gcc-sc8180x.ko
:kernel/drivers/clk/qcom/gcc-sm8150.ko
kernel/drivers/cpufreq/qcom-cpufreq-hw.ko
