:kernel/drivers/clk/qcom/clk-qcom.ko
kernel/drivers/i2c/i2c-mux.ko
:kernel/drivers/soc/qcom/boot_stats.ko
kernel/drivers/i2c/busses/i2c-msm-geni.ko
kernel/drivers/i2c/muxes/i2c-mux-pca954x.ko
kernel/drivers/gpu/drm/bridge/analogix/anx7625.ko
kernel/drivers/spmi/spmi-pmic-arb.ko
:extra/hdcp_qseecom_dlkm.ko
extra/msm_drm.ko
