:kernel/drivers/soc/qcom/qcom_rpmh.ko
:kernel/drivers/soc/qcom/mdt_loader.ko
:kernel/drivers/clk/qcom/clk-qcom.ko
kernel/drivers/clk/qcom/gpucc-sm8150.ko
:kernel/drivers/soc/qcom/llcc-qcom.ko
:kernel/drivers/iommu/qcom_iommu_util.ko
:kernel/drivers/nvmem/nvmem_qcom-spmi-sdam.ko
kernel/drivers/nvmem/nvmem_qfprom.ko
extra/msm_kgsl.ko
