# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

>mask=17
kernel/drivers/phy/qualcomm/phy-qcom-qmp-ufs.ko
kernel/drivers/ufs/core/ufshcd-core.ko
kernel/drivers/ufs/host/ufshcd-pltfrm.ko
:kernel/drivers/dma/qcom/gpi.ko
kernel/drivers/ufs/host/ufs-qcom.ko
@dm_create_tasklet
@wait_rootfs_tasklet
