# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

>mask=16
kernel/drivers/soc/qcom/qcom-geni-se.ko
kernel/drivers/soc/qcom/qcom_ccu_qup.ko
kernel/drivers/dma/qcom/gpi.ko
kernel/drivers/tty/serial/qcom_geni_serial.ko
kernel/drivers/soc/qcom/socinfo.ko
kernel/drivers/i2c/busses/i2c-qcom-geni.ko
