# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

>mask=15
extra/tz_ffi.ko
extra/dice_vm.ko
extra/apps_pinctrl.ko
extra/iommu_iova_map.ko
extra/scm_user_intf.ko
extra/scm_user_intf_sec.ko
extra/kiumd.ko
extra/kiumd_kgsl.ko
kernel/drivers/phy/qualcomm/phy-qcom-sgmii-eth.ko
:kernel/drivers/net/pcs/pcs_xpcs.ko
kernel/drivers/net/ethernet/stmicro/stmmac/stmmac.ko
kernel/drivers/net/ethernet/stmicro/stmmac/stmmac-platform.ko
:kernel/drivers/ufs/host/ufshcd-pltfrm.ko
kernel/drivers/net/ethernet/stmicro/stmmac/dwmac-qcom-ethqos.ko
