# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

>mask=15
extra/apps_pinctrl.ko
extra/iommu_iova_map.ko
extra/scm_user_intf.ko
extra/scm_user_intf_sec.ko
kernel/drivers/vfio/platform/vfio-platform-base.ko
kernel/drivers/vfio/platform/vfio-platform.ko
extra/kiumd.ko
extra/kiumd_kgsl.ko
extra/vfio_iommu_qcom.ko
extra/arm-smmu-qcom-fusa.ko
extra/pinctrl_fusa.ko
extra/vendor_uscmi.ko
extra/qcom_vdev.ko
