# Copyright (c) 2025 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

>mask=5
kernel/drivers/soc/qcom/smcinvoke/qcom_smcinvoke.ko
extra/qcom_uscmi.ko
extra/kryo_arm64_edac.ko
kernel/drivers/soc/qcom/socinfo.ko
