# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

>mask=14
kernel/drivers/vfio/platform/vfio-platform-base.ko
kernel/drivers/vfio/platform/vfio-platform.ko
extra/vfio_iommu_qcom.ko
extra/arm-smmu-qcom-fusa.ko
extra/pinctrl_fusa.ko
extra/qcom_vdev.ko
kernel/net/ipv6/ipv6.ko
