# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

>mask=13
:kernel/drivers/mailbox/qcom-ipcc.ko
:kernel/drivers/soc/qcom/qcom-geni-se.ko
extra/qcom_uscmi.ko
