# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

>mask=13
kernel/drivers/pinctrl/qcom/pinctrl-msm.ko
kernel/drivers/pinctrl/qcom/pinctrl-sa8797p.ko
kernel/drivers/net/phy/marvell.ko
kernel/drivers/net/phy/aquantia/aquantia.ko
extra/kryo_arm64_edac.ko
kernel/drivers/virtio/virtio_mmio.ko
kernel/drivers/mailbox/qcom-ipcc.ko
extra/qcom_uscmi.ko
