# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

>mask=12
kernel/drivers/soc/qcom/mdt_loader.ko
:extra/gh_rm_drv.ko
extra/hvc_gunyah.ko
extra/msm_hab.ko
extra/hyp-udmabuf.ko
