# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

>mask=11
extra/gh_msgq.ko
extra/gh_dbl.ko
extra/gh_arm_drv.ko
extra/gh_rm_drv.ko
extra/gh_ctrl.ko
extra/gunyah_info.ko
:kernel/drivers/soc/qcom/mdt_loader.ko
extra/gunyah.ko
