>mask=4
extra/apps_pinctrl.ko
extra/scm_user_intf.ko
extra/scm_user_intf_sec.ko
kernel/drivers/vfio/platform/vfio-platform-base.ko
kernel/drivers/vfio/platform/vfio-platform.ko
extra/vfio_iommu_qcom.ko
