cmd-db.ko
cqhci.ko
debug-regulator.ko
debug_symbol.ko
deferred-free-helper.ko
gh_arm_drv.ko
gh_dbl.ko
gh_msgq.ko
gh_rm_drv.ko
gh_vcpu_mgr.ko
iommu-logger.ko
llcc-qcom.ko
msm_dma_iommu_mapping.ko
nvmem_qcom-spmi-sdam.ko
phy-qcom-ufs.ko
phy-qcom-ufs-qmp-v4-canoe.ko
proxy-consumer.ko
qcom_cpucp.ko
qcom_hwspinlock.ko
clk-scmi.ko
qcom-ipcc.ko
qcom_llcc_pmu.ko
qcom-reboot-reason.ko
qcom_scmi_client.ko
qcom_scmi_vendor.ko
qcom-scm.ko
qcom_sdei.ko
qnoc-qos.ko
qseecom_proxy.ko
qti-regmap-debugfs.ko
sched-walt-debug.ko
secure_buffer.ko
sg.ko
smem.ko
socinfo.ko
stub-regulator.ko
gh_mem_notifier.ko
mem-prot.ko
gh_rm_heap_manager.ko
mem_buf_dev.ko
mem_buf_msgq.ko
mem_buf.ko
qcom_dma_heaps.ko
minidump.ko
qcom_ipc_logging.ko
qcom_aoss.ko
msm_qmp.ko
qcom-pdc.ko
qcom-dload-mode.ko
qcom_wdt_core.ko
qcom_cpu_vendor_hooks.ko
qcom_iommu_util.ko
crm-v2.ko
qcom_rpmh.ko
rpmh-regulator.ko
gdsc-regulator.ko
icc-bcm-voter.ko
icc-clk.ko
icc-debug.ko
icc-rpmh.ko
clk-qcom.ko
clk-dummy.ko
clk-rpmh.ko
gcc-canoe.ko
dispcc-canoe.ko
mdt_loader.ko
pinctrl-msm.ko
pinctrl-canoe.ko
qcom_ice.ko
sched-walt.ko
ufshcd-crypto-qti.ko
ufs-qcom.ko
cambistmclkcc-canoe.ko
camcc-canoe.ko
cpucp_fast.ko
dcvs_fp.ko
debugcc-canoe.ko
evacc-canoe.ko
gic_intr_routing.ko
gpucc-canoe.ko
msm_gpi.ko
i2c-msm-geni.ko
memory_dump_v2.ko
pinctrl-chora.ko
qcom-dcvs.ko
qcom_iommu_debug.ko
qcom_logbuf_boot_log.ko
qcom_logbuf_vendor_hooks.ko
qcom-pmu-lib.ko
qcom_soc_wdt.ko
spmi-pmic-arb.ko
qcom-spmi-pmic.ko
rtc-pm8xxx.ko
pmic-pon-log.ko
qcom_tsens.ko
qnoc-canoe.ko
qrtr.ko
sdhci-msm.ko
si_core_module.ko
tcsrcc-canoe.ko
videocc-canoe.ko
arm_smmu.ko
arm_smmu_pmu.ko
panel_event_notifier.ko
qcom_glink.ko
qcom_glink_smem.ko
qmi_helpers.ko
qcom_pdr_msg.ko
qcom_smd.ko
rproc_qcom_common.ko
pdr_interface.ko
qti_pmic_glink.ko
qti_battery_charger.ko
wcd_usbss_i2c.ko
extra/q6_pdr_dlkm.ko
extra/q6_notifier_dlkm.ko
extra/q6_dlkm.ko
extra/snd_event_dlkm.ko
extra/gpr_dlkm.ko
extra/spf_core_dlkm.ko
extra/audpkt_ion_dlkm.ko
extra/audio_pkt_dlkm.ko
extra/adsp_loader_dlkm.ko
extra/audio_prm_dlkm.ko
extra/pinctrl_lpi_dlkm.ko
extra/swr_dlkm.ko
extra/simple_amp_dlkm.ko
extra/stub_dlkm.ko
extra/wcd_core_dlkm.ko
extra/wcd9xxx_dlkm.ko
extra/wcd9378_slave_dlkm.ko
extra/wcd938x_slave_dlkm.ko
extra/wcd939x_slave_dlkm.ko
extra/wsa883x_dlkm.ko
extra/swr_ctrl_dlkm.ko
extra/mbhc_dlkm.ko
extra/wcd938x_dlkm.ko
extra/wcd939x_dlkm.ko
extra/swr_dmic_dlkm.ko
extra/swr_haptics_dlkm.ko
extra/lpass_cdc_dlkm.ko
extra/lpass_cdc_rx_macro_dlkm.ko
extra/lpass_cdc_tx_macro_dlkm.ko
extra/lpass_cdc_va_macro_dlkm.ko
extra/lpass_cdc_wsa2_macro_dlkm.ko
extra/lpass_cdc_wsa_macro_dlkm.ko
extra/wsa884x_dlkm.ko
extra/wcd9378_dlkm.ko
extra/machine_dlkm.ko
@dm_create_tasklet
@wait_rootfs_tasklet
