phy-qcom-ufs.ko
phy-qcom-ufs-qmp-v4-canoe.ko
icc-clk.ko
:qcom-scm.ko
iommu-logger.ko
qcom_iommu_util.ko
arm_smmu.ko
qcom_ice.ko
ufshcd-crypto-qti.ko
:minidump.ko
:crm-v2.ko
:proxy-consumer.ko
:debug-regulator.ko
gdsc-regulator.ko
clk-qcom.ko
:socinfo.ko
sched-walt.ko
:sched-walt.ko
:clk-qcom.ko
:qcom_ipc_logging.ko
:smem.ko
ufs-qcom.ko
boot_stats.ko
icc-debug.ko
qnoc-qos.ko
llcc-qcom.ko
nvmem_qcom-spmi-sdam.ko
qcom_llcc_pmu.ko
rtc-pm8xxx.ko
spmi-pmic-arb.ko
arm_smmu_pmu.ko
pinctrl-msm.ko
pinctrl-canoe.ko
pinctrl-chora.ko
gic_intr_routing.ko
mdt_loader.ko
gunyah_loader.ko
mem_buf.ko
:qcom_rpmh.ko
:cmd-db.ko
clk-rpmh.ko
dcvs_fp.ko
icc-bcm-voter.ko
cambistmclkcc-canoe.ko
camcc-canoe.ko
clk-dummy.ko
debugcc-canoe.ko
dispcc-canoe.ko
evacc-canoe.ko
gcc-canoe.ko
gpucc-canoe.ko
tcsrcc-canoe.ko
videocc-canoe.ko
:qcom_scmi_client.ko
cpucp_fast.ko
icc-rpmh.ko
qnoc-canoe.ko
msm_gpi.ko
i2c-msm-geni.ko
memory_dump_v2.ko
qcom_aoss.ko
msm_qmp.ko
:qcom_wdt_core.ko
:debug_symbol.ko
qcom_cpu_vendor_hooks.ko
qcom-dcvs.ko
qcom-pdc.ko
qcom-pmu-lib.ko
qcom_soc_wdt.ko
:qti-regmap-debugfs.ko
qcom-spmi-pmic.ko
rpmh-regulator.ko
