qmi_helpers.ko
qcom_pdr_msg.ko
:qcom_ipc_logging.ko
qcom_glink.ko
:smem.ko
qcom_glink_smem.ko
qcom_smd.ko
rproc_qcom_common.ko
pdr_interface.ko
qrtr.ko
qti_pmic_glink.ko
:panel_event_notifier.ko
qti_battery_charger.ko
:qti-regmap-debugfs.ko
wcd_usbss_i2c.ko
