extra/snd_event_dlkm.ko
extra/q6_dlkm.ko
extra/stub_dlkm.ko
extra/swr_dlkm.ko
:pdr_interface.ko
extra/q6_pdr_dlkm.ko
:rproc_qcom_common.ko
extra/q6_notifier_dlkm.ko
extra/gpr_dlkm.ko
extra/spf_core_dlkm.ko
extra/adsp_loader_dlkm.ko
:qcom-scm.ko
extra/audpkt_ion_dlkm.ko
:qcom_ipc_logging.ko
extra/audio_pkt_dlkm.ko
extra/audio_prm_dlkm.ko
:qti-regmap-debugfs.ko
extra/lpass_cdc_dlkm.ko
:pinctrl-msm.ko
extra/wcd_core_dlkm.ko
extra/swr_ctrl_dlkm.ko
extra/lpass_cdc_rx_macro_dlkm.ko
extra/lpass_cdc_tx_macro_dlkm.ko
extra/lpass_cdc_va_macro_dlkm.ko
extra/lpass_cdc_wsa2_macro_dlkm.ko
extra/lpass_cdc_wsa_macro_dlkm.ko
extra/wcd9xxx_dlkm.ko
:wcd_usbss_i2c.ko
extra/mbhc_dlkm.ko
extra/wcd9378_dlkm.ko
extra/wcd939x_slave_dlkm.ko
extra/wcd939x_dlkm.ko
extra/wsa883x_dlkm.ko
extra/wsa884x_dlkm.ko
:socinfo.ko
extra/machine_dlkm.ko
extra/pinctrl_lpi_dlkm.ko
extra/simple_amp_dlkm.ko
extra/swr_dmic_dlkm.ko
:qti_battery_charger.ko
extra/swr_haptics_dlkm.ko
extra/wcd9378_slave_dlkm.ko
extra/wcd938x_dlkm.ko
extra/wcd938x_slave_dlkm.ko
qcom_tsens.ko
@dm_create_tasklet
@wait_rootfs_tasklet