kernel/drivers/clk/qcom/gcc-sa7255p.ko
kernel/drivers/pinctrl/qcom/pinctrl-msm.ko
kernel/drivers/pinctrl/qcom/pinctrl-sa7255p.ko
kernel/drivers/mailbox/qcom-ipcc.ko
kernel/drivers/soc/qcom/rpmhpd.ko
kernel/drivers/soc/qcom/qcom-geni-se.ko
kernel/drivers/tty/serial/qcom_geni_serial.ko
kernel/drivers/interconnect/qcom/qnoc-sa7255p.ko
kernel/drivers/regulator/qcom-rpmh-regulator.ko
kernel/drivers/phy/qualcomm/phy-qcom-qmp-ufs.ko
kernel/drivers/devfreq/governor_simpleondemand.ko
kernel/drivers/ufs/core/ufshcd-core.ko
kernel/drivers/ufs/host/ufshcd-pltfrm.ko
kernel/drivers/ufs/host/ufs-qcom.ko
kernel/drivers/spmi/spmi-pmic-arb.ko
kernel/drivers/pinctrl/qcom/pinctrl-spmi-gpio.ko
kernel/drivers/pinctrl/qcom/pinctrl-spmi-mpp.ko
kernel/drivers/nvmem/nvmem_qcom-spmi-sdam.ko
kernel/drivers/net/phy/marvell.ko
kernel/drivers/clk/qcom/camcc-sa8775p.ko
kernel/drivers/clk/qcom/dispcc-sa7255p.ko
kernel/drivers/clk/qcom/gpucc-sa8775p.ko
kernel/drivers/clk/qcom/videocc-sa8775p.ko
@wait_rootfs_tasklet
