kernel/drivers/spmi/spmi-pmic-arb.ko
kernel/drivers/pinctrl/qcom/pinctrl-spmi-gpio.ko
kernel/drivers/pinctrl/qcom/pinctrl-spmi-mpp.ko
kernel/drivers/nvmem/nvmem_qcom-spmi-sdam.ko
kernel/drivers/net/phy/marvell.ko
kernel/drivers/clk/qcom/camcc-sa8775p.ko
kernel/drivers/clk/qcom/dispcc-sa7255p.ko
kernel/drivers/clk/qcom/gpucc-sa8775p.ko
kernel/drivers/clk/qcom/videocc-sa8775p.ko
@dm_create_tasklet
@wait_rootfs_tasklet
