>mask=0
kernel/drivers/pinctrl/qcom/pinctrl-msm.ko
kernel/drivers/pinctrl/qcom/pinctrl-sa8775p.ko
kernel/drivers/soc/qcom/qcom_ice.ko
kernel/drivers/phy/qualcomm/phy-qcom-qmp-ufs.ko
kernel/drivers/ufs/core/ufshcd-core.ko
kernel/drivers/ufs/host/ufshcd-pltfrm.ko
:kernel/drivers/mailbox/qcom-ipcc.ko
:kernel/drivers/soc/qcom/qcom-geni-se.ko
kernel/drivers/ufs/host/ufs-qcom.ko
@dm_create_tasklet
@wait_rootfs_tasklet
