>mask=4
extra/tz_ffi.ko
extra/apps_pinctrl.ko
extra/iommu_iova_map.ko
extra/scm_user_intf.ko
extra/scm_user_intf_sec.ko
kernel/drivers/vfio/platform/vfio-platform-base.ko
kernel/drivers/vfio/platform/vfio-platform.ko
extra/kiumd.ko
extra/kiumd_kgsl.ko
extra/qcom_vdev.ko
extra/vfio_iommu_qcom.ko
extra/ipcc_shmem_test_module.ko
