extra/ipcc_shmem_test_module.ko
kernel/drivers/spi/spidev.ko
kernel/drivers/soc/qcom/smcinvoke/qcom_smcinvoke.ko
extra/qcom_dload_mode.ko
extra/qcom_uscmi.ko
extra/mhi_ep_net.ko
extra/kryo_arm64_edac.ko
kernel/drivers/soc/qcom/socinfo.ko
