>mask=5
kernel/drivers/soc/qcom/smcinvoke/qcom_smcinvoke.ko
extra/qcom_uscmi.ko
extra/kryo_arm64_edac.ko
kernel/drivers/virtio/virtio_mmio.ko
kernel/drivers/mailbox/qcom-ipcc.ko
:kernel/drivers/soc/qcom/qcom-geni-se.ko
kernel/drivers/tty/serial/qcom_geni_serial.ko
kernel/drivers/soc/qcom/socinfo.ko
