kernel/drivers/clk/qcom/clk-qcom.ko
kernel/drivers/clk/qcom/gcc-sa8775p.ko
kernel/drivers/pinctrl/qcom/pinctrl-msm.ko
kernel/drivers/pinctrl/qcom/pinctrl-sa8775p.ko
kernel/drivers/soc/qcom/cmd-db.ko
kernel/drivers/soc/qcom/qcom_rpmh.ko
kernel/drivers/clk/qcom/clk-rpmh.ko
kernel/drivers/soc/qcom/rpmhpd.ko
kernel/drivers/soc/qcom/qcom-geni-se.ko
kernel/drivers/tty/serial/qcom_geni_serial.ko
kernel/drivers/interconnect/qcom/icc-bcm-voter.ko
kernel/drivers/interconnect/qcom/icc-rpmh.ko
kernel/drivers/interconnect/qcom/qnoc-sa8775p.ko
kernel/drivers/regulator/qcom-rpmh-regulator.ko
kernel/drivers/phy/qualcomm/phy-qcom-qmp-ufs.ko
kernel/fs/mbcache.ko
kernel/fs/jbd2/jbd2.ko
kernel/fs/ext4/ext4.ko
kernel/drivers/devfreq/governor_simpleondemand.ko
kernel/drivers/ufs/core/ufshcd-core.ko
kernel/drivers/ufs/host/ufshcd-pltfrm.ko
kernel/drivers/ufs/host/ufs_qcom.ko
kernel/drivers/clk/qcom/camcc-sa8775p.ko
kernel/drivers/clk/qcom/dispcc0-sa8775p.ko
kernel/drivers/clk/qcom/dispcc1-sa8775p.ko
kernel/drivers/clk/qcom/gpucc-sa8775p.ko
kernel/drivers/clk/qcom/videocc-sa8775p.ko
@wait_rootfs_tasklet
