extra/apps_pinctrl.ko
kernel/drivers/iommu/iommufd/iommufd.ko
kernel/drivers/vfio/vfio.ko
extra/iommu_iova_map.ko
extra/scm_user_intf.ko
kernel/drivers/vfio/vfio_iommu_type1.ko
kernel/drivers/vfio/platform/vfio-platform-base.ko
kernel/drivers/vfio/platform/vfio-platform.ko
extra/kiumd.ko
extra/kiumd_kgsl.ko
extra/vfio_iommu_qcom.ko
