extra/ipcc_shmem_test_module.ko
kernel/drivers/soc/qcom/smem.ko
extra/minidump.ko
extra/gh_msgq.ko
extra/gh_dbl.ko
extra/gh_arm_drv.ko
extra/gh_rm_drv.ko
extra/hvc_gunyah.ko
extra/hyp-udmabuf.ko
kernel/drivers/soc/qcom/mdt_loader.ko
extra/gunyah.ko
kernel/drivers/i2c/busses/i2c-qcom-geni.ko
kernel/drivers/i2c/i2c-dev.ko
extra/qcom_scm_oot.ko
extra/qtee_shmbridge.ko
extra/smcinvoke.ko
kernel/drivers/spi/spidev.ko
extra/qcom_dload_mode.ko
extra/qcom_uscmi.ko
extra/mhi_ep_net.ko
extra/kryo_arm64_edac.ko
kernel/drivers/soc/qcom/socinfo.ko
kernel/drivers/hwspinlock/qcom_hwspinlock.ko
