smem.ko
extra/socinfo_dt.ko
virtio_mmio.ko
failover.ko
net_failover.ko
virtio_net.ko
gh_dbl.ko
gh_msgq.ko
gh_arm_drv.ko
gh_rm_drv.ko
msm_hab.ko
crypto-qti-virt.ko
virtio_blk_qti_crypto.ko
virtio_block.ko
<<<<<<< HEAD   (578349 Merge db423771208a3af5930754e7ebdee61c3b1b1b42 on remote bra)
extra/socinfo_dt.ko
=======
extra/boot_marker.ko
>>>>>>> CHANGE (20f20f early-ramdisk: read socinfo and run unification)
@dm_create_tasklet
@wait_rootfs_tasklet
@fetch_socinfo_tasklet
